# .github/workflows/deploy.yml

name: 📦 Deploy site to S3 & CloudFront

on:
  push:
    branches: [ main ]    # ← or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get the code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3️⃣ Install dependencies and build
      - name: Install & build
        run: |
          npm ci
          npm run build

      # 4️⃣ Configure AWS credentials from your repository secrets
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1    # your bucket's region

      # 5️⃣ List S3 buckets (for debugging)
      - name: List S3 buckets
        run: |
          echo "Listing available S3 buckets..."
          aws s3 ls || echo "Failed to list buckets - check AWS credentials"

      # 6️⃣ Sync files up to S3
      - name: Sync to S3
        run: |
          echo "Attempting to sync to S3 bucket..."
          aws s3 sync ./dist s3://withbalancehealth.com --delete || {
            echo "Failed to sync to S3"
            exit 1
          }

      # 7️⃣ Invalidate CloudFront
      - name: Invalidate CloudFront cache
        if: success()
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id ERJE11J9LDERJ \
            --paths "/*" || {
              echo "Failed to invalidate CloudFront cache"
              exit 1
            }
